import fs from "node:fs";
import path from "node:path";
import { scanStack, type StackProfile } from "./stack-detector.js";
import { buildContext } from "./context-builder.js";
import {
  renderToString,
  writeClaudeMd,
  checkStaleness,
} from "./claude-md-writer.js";
import type { ProjectContext } from "./claude-md-writer.js";

export interface DevFlags {
  smart?: boolean;
  noLaunch?: boolean;
  force?: boolean;
  diff?: boolean;
}

export interface DevResult {
  success: boolean;
  generated: boolean;
  skippedReason?: string;
  diff?: string;
  context?: ProjectContext;
  error?: string;
}

function ensureGitignore(projectPath: string): void {
  const gitignorePath = path.join(projectPath, ".gitignore");
  if (!fs.existsSync(gitignorePath)) return;
  const content = fs.readFileSync(gitignorePath, "utf-8");
  if (content.includes("CLAUDE.md")) return;
  fs.appendFileSync(gitignorePath, "\n# Generated by aman-agent dev\nCLAUDE.md\n");
}

export async function runDev(
  projectPath: string,
  flags: DevFlags = {},
  precomputedStack?: StackProfile,
): Promise<DevResult> {
  const resolved = path.resolve(projectPath);

  if (!fs.existsSync(resolved)) {
    return { success: false, generated: false, error: `Directory not found: ${resolved}` };
  }

  const stack = precomputedStack ?? scanStack(resolved);

  // Handle --diff
  if (flags.diff) {
    const ctx = await buildContext(stack, { smart: flags.smart });
    const newContent = renderToString(ctx);
    const existingPath = path.join(resolved, "CLAUDE.md");
    const existing = fs.existsSync(existingPath)
      ? fs.readFileSync(existingPath, "utf-8")
      : "";
    return {
      success: true,
      generated: false,
      diff: existing === newContent ? "(no changes)" : newContent,
      context: ctx,
    };
  }

  // Check staleness
  if (!flags.force) {
    const staleness = checkStaleness(resolved);
    if (staleness.status === "fresh") {
      return { success: true, generated: false, skippedReason: "fresh" };
    }
  }

  // Build context and write
  const ctx = await buildContext(stack, { smart: flags.smart });
  const writeResult = writeClaudeMd(ctx, resolved);

  ensureGitignore(resolved);

  return {
    success: true,
    generated: writeResult.written,
    context: ctx,
  };
}
