import fs from "node:fs";
import path from "node:path";
import { scanStack, type StackProfile } from "./stack-detector.js";
import { buildContext } from "./context-builder.js";
import {
  renderToString,
  writeContextFile,
  checkStaleness,
  EDITOR_TARGETS,
  type EditorName,
} from "./claude-md-writer.js";
import type { ProjectContext } from "./claude-md-writer.js";

export interface DevFlags {
  smart?: boolean;
  noLaunch?: boolean;
  force?: boolean;
  diff?: boolean;
  editor?: EditorName;
}

export interface DevResult {
  success: boolean;
  generated: boolean;
  skippedReason?: string;
  diff?: string;
  context?: ProjectContext;
  error?: string;
}

function ensureGitignore(projectPath: string, editor: EditorName): void {
  const gitignorePath = path.join(projectPath, ".gitignore");
  if (!fs.existsSync(gitignorePath)) return;
  const content = fs.readFileSync(gitignorePath, "utf-8");
  const target = EDITOR_TARGETS[editor];
  if (content.includes(target.gitignoreEntry)) return;
  fs.appendFileSync(gitignorePath, `\n# Generated by aman-agent dev\n${target.gitignoreEntry}\n`);
}

export async function runDev(
  projectPath: string,
  flags: DevFlags = {},
  precomputedStack?: StackProfile,
): Promise<DevResult> {
  const resolved = path.resolve(projectPath);
  const editor = flags.editor ?? "claude";

  if (!fs.existsSync(resolved)) {
    return { success: false, generated: false, error: `Directory not found: ${resolved}` };
  }

  const stack = precomputedStack ?? scanStack(resolved);

  // Handle --diff
  if (flags.diff) {
    const ctx = await buildContext(stack, { smart: flags.smart });
    const newContent = renderToString(ctx);
    const target = EDITOR_TARGETS[editor];
    const existingPath = path.join(resolved, target.contextFile);
    const existing = fs.existsSync(existingPath)
      ? fs.readFileSync(existingPath, "utf-8")
      : "";
    return {
      success: true,
      generated: false,
      diff: existing === newContent ? "(no changes)" : newContent,
      context: ctx,
    };
  }

  // Check staleness
  // --smart always regenerates (user explicitly wants LLM synthesis)
  if (!flags.force && !flags.smart) {
    const staleness = checkStaleness(resolved, editor);
    if (staleness.status === "fresh") {
      // Check if context file is older than 1 hour — if so, regenerate
      if (staleness.generatedAt) {
        const ageMs = Date.now() - staleness.generatedAt.getTime();
        const ONE_HOUR = 60 * 60 * 1000;
        if (ageMs < ONE_HOUR) {
          return { success: true, generated: false, skippedReason: "fresh" };
        }
      } else {
        return { success: true, generated: false, skippedReason: "fresh" };
      }
    }
  }

  // Build context and write
  const ctx = await buildContext(stack, { smart: flags.smart });
  writeContextFile(ctx, resolved, editor);

  ensureGitignore(resolved, editor);

  return {
    success: true,
    generated: true,
    context: ctx,
  };
}
